<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-31 11:00
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-31 11:00
=======
# Generated by Django 3.2 on 2021-05-27 04:51
>>>>>>> 6770016... commit
=======
# Generated by Django 3.2 on 2021-05-27 13:24
>>>>>>> cd6ce12... social login
<<<<<<< HEAD
>>>>>>> d5fa9d3... social login
=======
=======
# Generated by Django 3.2.3 on 2021-05-29 13:21
>>>>>>> 666ebdc... auth_email
<<<<<<< HEAD
>>>>>>> b091a65... auth_email
=======
=======
# Generated by Django 3.2 on 2021-05-27 13:24
>>>>>>> a94e80e... social login
<<<<<<< HEAD
>>>>>>> 65f2a33... dev
=======
=======
# Generated by Django 3.2.3 on 2021-06-01 10:06
>>>>>>> f5972cb... upload
>>>>>>> 58262ea... upload

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.TimeField(default=datetime.time(15, 0))),
                ('checkout', models.TimeField(default=datetime.time(11, 0))),
            ],
            options={
                'db_table': 'able_times',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=2000)),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'amenities',
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
                'db_table': 'amenities',
=======
                'db_table': 'amentities',
>>>>>>> 6770016... commit
=======
                'db_table': 'amentities',
>>>>>>> cd6ce12... social login
<<<<<<< HEAD
>>>>>>> d5fa9d3... social login
=======
=======
                'db_table': 'amentities',
>>>>>>> 666ebdc... auth_email
<<<<<<< HEAD
>>>>>>> b091a65... auth_email
=======
=======
                'db_table': 'amentities',
>>>>>>> a94e80e... social login
>>>>>>> 65f2a33... dev
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DisableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> d5fa9d3... social login
=======
>>>>>>> b091a65... auth_email
=======
<<<<<<< HEAD
>>>>>>> 65f2a33... dev
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'disable_dates',
<<<<<<< HEAD
=======
=======
=======
>>>>>>> cd6ce12... social login
=======
>>>>>>> 666ebdc... auth_email
=======
>>>>>>> a94e80e... social login
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'disalbe_dates',
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 6770016... commit
=======
>>>>>>> cd6ce12... social login
<<<<<<< HEAD
>>>>>>> d5fa9d3... social login
=======
=======
>>>>>>> 666ebdc... auth_email
<<<<<<< HEAD
>>>>>>> b091a65... auth_email
=======
=======
>>>>>>> a94e80e... social login
>>>>>>> 65f2a33... dev
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('min_date', models.CharField(default='1', max_length=32)),
                ('city', models.CharField(max_length=32)),
<<<<<<< HEAD
                ('capacity', models.IntegerField(default='2', max_length=32)),
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
                ('capacity', models.IntegerField(default='2', max_length=32)),
=======
                ('capacity', models.CharField(default='2', max_length=32)),
>>>>>>> 6770016... commit
=======
                ('capacity', models.CharField(default='2', max_length=32)),
>>>>>>> cd6ce12... social login
<<<<<<< HEAD
>>>>>>> d5fa9d3... social login
=======
=======
                ('capacity', models.CharField(default='2', max_length=32)),
>>>>>>> 666ebdc... auth_email
<<<<<<< HEAD
>>>>>>> b091a65... auth_email
=======
=======
                ('capacity', models.CharField(default='2', max_length=32)),
>>>>>>> a94e80e... social login
>>>>>>> 65f2a33... dev
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_refund', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'room_amenities',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_wish', to='room.room')),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
    ]
