# Generated by Django 3.2.3 on 2021-05-31 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledate',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='disabledate',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='disable_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='room.disabledate'),
        ),
        migrations.AlterModelTable(
            name='amenity',
            table='amenities',
        ),
        migrations.AlterModelTable(
            name='disabledate',
            table='disable_dates',
        ),
    ]
