<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-31 11:00

from django.db import migrations, models
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-31 11:00

from django.db import migrations, models
=======
>>>>>>> e1d39bb... commit
=======
# Generated by Django 3.2.3 on 2021-05-29 13:21

from django.db import migrations, models
>>>>>>> 666ebdc... auth_email
<<<<<<< HEAD
>>>>>>> b091a65... auth_email
=======
=======
# Generated by Django 3.2 on 2021-05-27 13:24

from django.db import migrations, models
>>>>>>> a94e80e... social login
>>>>>>> 65f2a33... dev
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('cleanliness', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('communication', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('checkin', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('accuracy', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('location', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('cost_effectivenes', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('review_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_review', to='room.room')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, null=True, unique=True)),
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
                ('social_id', models.CharField(max_length=128, null=True, unique=True)),
=======
                ('social_id', models.CharField(max_length=200, unique=True)),
>>>>>>> e140d10... commit
=======
>>>>>>> 666ebdc... auth_email
=======
                ('social_id', models.CharField(max_length=200, unique=True)),
>>>>>>> a94e80e... social login
                ('first_name', models.CharField(max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=32, null=True, unique=True)),
                ('birthday', models.CharField(max_length=32, null=True)),
                ('sex', models.CharField(max_length=32, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('profile_url', models.CharField(max_length=2000, null=True)),
<<<<<<< HEAD
<<<<<<< HEAD
                ('is_auth', models.BooleanField(default=False)),
=======
                ('is_active', models.BooleanField(default=False)),
>>>>>>> 666ebdc... auth_email
=======
>>>>>>> a94e80e... social login
                ('review', models.ManyToManyField(related_name='user', through='user.Review', to='user.User')),
                ('wishlist', models.ManyToManyField(related_name='user', through='room.WishList', to='room.Room')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='user.user'),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='user.user')),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
    ]
