# Generated by Django 3.2 on 2021-05-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
