# Generated by Django 3.2.3 on 2021-06-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_auth',
            new_name='is_allowed',
        ),
    ]
