# Generated by Django 3.2.3 on 2021-05-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_active_user_is_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_auth',
            new_name='is_allowed',
        ),
    ]
